### ISSUE TITLE
Can you please create a mod 

### ISSUE THREAD

**Issue by ghost** [GitFyu/ShinyPots#4]
Hi ,
So I just wanted to tell can you make a mod for me like
Shiny pots but can you add the glowing effect on the enchanted items and can you make this mod for 1.8.9. like the glitch on badlion client the swords and axes etc.. the get the glowing effect can you possibly make it for forge?.
Please create this mod :)

**Comment by gitfyu** [comment]
I don't make mods anymore, sorry
